config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path:'', path_names: {sign_in: 'login', sign_out: 'logout', sign_up: 'register'}
  resources :portfolios, except: [:show]     #vid 66 customroute for show
    get 'portfolio/:id' , to: 'portfolios#show', as:'portfolio_show'

    get 'angular_items' , to: 'portfolios#angular'  #path of custom scope angular

  #customizing the routes vid 65
  root to: 'pages#home'   #for home/main page

  #get 'pages/about'  
  get 'about-me' , to:'pages#about'  #u can customize the get part with any name

  get 'contact' , to:'pages#contact'
 

  resources :blogs


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/portfolio.rb
#portfolio model

class Portfolio < ApplicationRecord  #this portfolio is been called in portfolio cotroller
	has_many :technologies
	 
	 accepts_nested_attributes_for :technologies,  #Nested attributes in model meanas angular ruby for technology vid 83
	    reject_if: lambda { |attrs| attrs['name'].blank? }

	include Placeholder
	validates_presence_of :title, :body, :main_image, :thumb_image

def self.angular        #alternate way to custom 
	where(subtitle:"Angular")
end

def self.by_position
	order("Position ASC")
end

scope :ruby_on_rails_portfolio_items , ->{  where(subtitle:"Ruby on Rails")}    #CUSTOM SCOPE VID 79  create same file as created for angular scope above method in one line

 after_initialize :set_defaults
 def set_defaults   #will set defaults values
 	self.main_image ||= Placeholder.image_generator(height:'600', width:'400')
 	self.thumb_image ||= Placeholder.image_generator(height:'350', width:'150')
 end
end

app/controllers/portfolios_controller.rb
#portfolio controller 22

class PortfoliosController < ApplicationController
	layout "portfolio" #pfolio layout included

	access all: [:show, :index, :angular], user: {except: [:destroy, :new, :create, :update, :edit]}, site_admin: :all #authorization
	
	def index
		@portfolio_items = Portfolio.by_position #calling from portfolio model
	end

	def angular
	@angular_portfolio_items= Portfolio.angular
	end  

	def new
		@portfolio_item= Portfolio.new
		3.times {@portfolio_item.technologies.build}
	end

	def create
		@portfolio_item = Portfolio.new(portfolio_params) #getting the parameter of form title nd body

    respond_to do |format|
      if @portfolio_item.save
        format.html { redirect_to portfolios_path, notice: "Portfolio item was successfully created." } #will redirect to blog show page
        
      else
        format.html { render :new, status: :unprocessable_entity }
        
     end
   end	
 end

 def edit
 	@portfolio_item = Portfolio.find(params[:id])
 
 end

def update
	@portfolio_item = Portfolio.find(params[:id])
	respond_to do |format|
      if @portfolio_item.update(portfolio_params)
        format.html { redirect_to portfolios_path, notice: "Blog was successfully updated." }
      
      else
        format.html { render :edit, status: :unprocessable_entity }
        
      end
    end
end

def show
	@portfolio_item = Portfolio.find(params[:id])
	end

def destroy

	#Perform the lookup
	@portfolio_item = Portfolio.find(params[:id])

	#destroy/delete the recode
	@portfolio_item.destroy

	#Will redirect to indexpage
    respond_to do |format|
      format.html { redirect_to portfolios_url, notice: "Portfolio item was successfully destroyed." }
      format.json { head :no_content }
    end
end

private
def portfolio_params
 params.require(:portfolio).permit(:title,
																   :subtitle,
																   :body
																   )
end

end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
end

app/views/portfolios/_form.html.erb
<%= form_with(model: @portfolio_item) do |form| %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :subtitle %>
    <%= form.text_field :subtitle %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

 <ul>
  <%= form.fields_for :technologies do |technology_form| %>
    <li>
      <%= technology_form.label :name %>
      <%= technology_form.text_field :name %>
    </li>
    <% end %>
  </ul>

  <div class="actions">
    <%= form.submit %>
  </div>

<% end %>

app/views/portfolios/_portfolio_item.html.erb
 <p> <%= link_to portfolio_item.title , portfolio_show_path(portfolio_item) %> </p>  <!--for show ACTION portfolio_item is actually getting the id rails itself knows this -->
 <p> <%= portfolio_item.subtitle %> </p>
 <p> <%= portfolio_item.body %> </p>
  <%= image_tag portfolio_item.thumb_image unless portfolio_item.thumb_image.nil? %> 
  <%= link_to "Edit Portfolio Item" , edit_portfolio_path(portfolio_item) if logged_in?(:site_admin) %>
  <%= link_to 'Delete portfolio item', portfolio_path(portfolio_item), method: :delete, data: { confirm: 'Are you sure?' } if logged_in?(:site_admin) %> 

app/views/portfolios/angular.html.erb
<!-- view 33 -->
<h1>Angular Portfolio Items</h1> 


<%= link_to "Create New Item" , new_portfolio_path if logged_in?(:site_admin)  %> 
<% @angular_portfolio_items.each do |portfolio_item|  %> <!-- portfolio _items is cmng from pfolio controller -->

 <p> <%= link_to portfolio_item.title , portfolio_show_path(portfolio_item) %> </p>  <!--for show ACTION portfolio_item is actually getting the id rails itself knows this -->

 <p> <%= portfolio_item.subtitle %> </p>
 <p> <%= portfolio_item.body %> </p>
 <%= image_tag portfolio_item.thumb_image unless portfolio_item.thumb_image.nil? %> 
  <%= link_to "Edit Portfolio Item" , edit_portfolio_path(portfolio_item) if logged_in?(:site_admin)  %>

  <%= link_to 'Delete portfolio item', portfolio_path(portfolio_item), method: :delete, data: { confirm: 'Are you sure?' } if logged_in?(:site_admin)  %> 



<% end %>

app/views/portfolios/edit.html.erb
<h1> Edit Portfolio Items</h1>

<%= render 'form', portfolio_item: @portfolio_item %>

app/views/portfolios/index.html.erb
<!-- view 33 -->
<h1>Portfolio Items</h1> 


<%= link_to "Create New Item" , new_portfolio_url if logged_in?(:site_admin) %> 
 <%= render partial: 'portfolio_item', collection: @portfolio_items %> <!-- pfolio_items is an instance var -->

app/views/portfolios/new.html.erb
<h1> New Portfolioo Items</h1>

<%= render 'form', portfolio_item: @portfolio_item %>

app/views/portfolios/show.html.erb
<h1> ---Show Page--- </h1>

<p> <%= image_tag @portfolio_item.main_image  %> </p>
<h1> <%= @portfolio_item.title  %> </h1>h
<em> <%= @portfolio_item.subtitle  %> </em>
<p> <%= @portfolio_item.body  %> </p>

<h1>Technologies used</h1>
<% @portfolio_item.technologies.each do |t| %>
<p> <%= t.name %> </p>
<% end %>

<hr>