config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path:'', path_names: {sign_in: 'login', sign_out: 'logout', sign_up: 'register'}
  resources :portfolios, except: [:show]     #vid 66 customroute for show
    get 'portfolio/:id' , to: 'portfolios#show', as:'portfolio_show'

    get 'angular_items' , to: 'portfolios#angular'  #path of custom scope angular

  #customizing the routes vid 65
  root to: 'pages#home'   #for home/main page

  #get 'pages/about'  
  get 'about-me' , to:'pages#about'  #u can customize the get part with any name

  get 'contact' , to:'pages#contact'
 

  resources :blogs


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/shared/_application_nav.html.erb
   <div class="masthead clearfix">
          <div class="inner">
            <h3 class="masthead-brand">Jorden Hugens</h3>
            <nav class="nav nav-masthead">
             <%= link_to "Home", root_path, class:'nav-link'%> 
             <%= link_to "About me", about_me_path, class:'nav-link'%> 
             <%= link_to "Contact", contact_path, class:'nav-link'%> 
             <%= link_to "Blogs", blogs_path, class:'nav-link'%> 
             <%= link_to "Portfolios", portfolios_path, class:'nav-link'%> 
             <%= login_helper('nav-link') %>   <!-- calling helper from app-helper-app-helper.rbbb fromapphtmlbr-->
             </nav>
          </div>
        </div>

app/views/shared/_nav.html.erb
<div class="<%= localize %>">
      
         <%= link_to "Home", root_path%> 
         <%= link_to "About me", about_me_path%> 
         <%= link_to "Contact", contact_path%> 
         <%= link_to "Blogs", blogs_path%> 
         <%= link_to "Portfolios", portfolios_path%> 
         
</div>